[workspace]

members = [
    "dossier",
    "dossier-core",
    "dossier-ts",
    "dossier-ts2",
]

[patch.crates-io]
tree-sitter = { git ="https://github.com/tree-sitter/tree-sitter.git", rev="660481d" }
